import React from 'react';
import { ArrowRight, Ship } from 'lucide-react';
import { Link } from 'react-router-dom';
import SEO from '../components/SEO';

const TransfersCharters: React.FC = () => {
  return <main className="bg-[#001219] text-[#F8F4E8]">
    <SEO title="Belize Boat Transfers & Private Charters" description="Request an Action Divers boat transfer between Belize International Airport and San Pedro, with proposed pricing confirmed by staff." path="/transfers-charters" image="/images/gallery/Three-of-a-Kind-boat-1.png" />
    <section className="relative flex min-h-[650px] items-end overflow-hidden px-5 pb-20 pt-32 sm:px-8 lg:px-14"><img src="/images/gallery/Three-of-a-Kind-boat-1.png" alt="Action Divers boat on the water in Belize" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#001219] via-[#001219]/50 to-[#001219]/15" /><div className="relative mx-auto w-full max-w-7xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#8DE7EF]">Private travel by water</p><h1 className="mt-5 max-w-5xl text-5xl font-extrabold tracking-[-0.045em] sm:text-7xl lg:text-8xl">Transfers & Charters</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-[#F8F4E8]/78">Tell us your flight, group, luggage, destination, and timing. Every transfer remains a request until staff confirms the route and price.</p></div></section>
    <section className="mx-auto grid max-w-7xl gap-14 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_0.8fr] lg:px-14"><div><p className="text-sm font-bold uppercase tracking-[0.14em] text-[#11C7D9]">Proposed pricing</p><h2 className="mt-4 text-4xl font-extrabold tracking-tight">Airport boat transfer</h2><div className="mt-9 divide-y divide-white/14 border-y border-white/14"><div className="flex justify-between gap-8 py-5"><span>1–6 passengers, one way</span><strong>$600 USD</strong></div><div className="flex justify-between gap-8 py-5"><span>Above 6 passengers</span><strong>$100 per passenger, per direction</strong></div><div className="flex justify-between gap-8 py-5"><span>Round trip</span><strong>Twice the one-way total</strong></div></div><p className="mt-5 text-sm leading-relaxed text-[#F8F4E8]/58">These are proposed examples, not confirmed fares. Staff will review the full itinerary before sending a final quote.</p></div><aside className="self-start border-l border-white/14 pl-0 lg:pl-10"><Ship className="h-10 w-10 text-[#11C7D9]" /><h2 className="mt-6 text-2xl font-extrabold">Start a transfer request</h2><p className="mt-4 leading-relaxed text-[#F8F4E8]/68">The dedicated form collects passengers, direction, flights, dates and times, luggage, destination, contact details, and special requirements.</p><Link to="/transfers-charters/request" className="mt-7 inline-flex min-h-12 items-center rounded-full bg-[var(--brand-orange)] px-6 font-bold text-white">Request a transfer <ArrowRight className="ml-2 h-4 w-4" /></Link></aside></section>
  </main>;
};
export default TransfersCharters;
